### ISSUE TITLE
Query Children in CAROUSEL_ALBUM

### ISSUE THREAD

**Issue by ttstauss** [oorestisime/gatsby-source-instagram#132]
Is it possible to query children in the CAROUSEL_ALBUM mediaType?

When I view the JSON in a web browser it returns an array of children (images, videos, etc.), however, when I query via GraphiQL the children nodes are blank.

**Comment by oorestisime** [comment]
Hello,

On which method are you talking? public scraping or using the graph api?

**Comment by ttstauss** [comment]
Using the graph api.

**Comment by oorestisime** [comment]
unfortunately i don't have this type of media type. i think adding them is not hard. do you want to give it a go? (since you can test it). or maybe provide me with a json example. 
this where it gets the data from the api https://github.com/oorestisime/gatsby-source-instagram/blob/master/src/instagram.js#L98
and here where it normalizes the different posts https://github.com/oorestisime/gatsby-source-instagram/blob/master/src/gatsby-node.js#L42

Keep in mind children is an internal gatsby field i don't think you will be able to name it like that. you might need to map it differently.

**Comment by ttstauss** [comment]
Ok, I'll try to take a look or see if I can get you a json example. Thanks!
