### ISSUE TITLE
Hashtag scraping

### ISSUE THREAD

**Issue by luchoster** [oorestisime/gatsby-source-instagram#18]
Hey thanks so much for creating this, I was about to start messing with IG and Gatsby yesterday, but IG went down (Thankfully).

I want to see if there's a way to scrape hashtags instead of the username for example. I want to pull all the posts that contain certain hashtag.

Thank you!

**Comment by oorestisime** [comment]
Interesting yes!

Right now it doesn't support this. Are you interested in the public scraping method? or using the Graph API? (because i think using the graph API would require more rights than the basic i think)
And just as a reminder, those nodes are created on build time. so you won't be able to pull off live data using this. I am mentioning this since hashtags are probable moving quite more quickly.

**Comment by luchoster** [comment]
I think using the Graph would be more useful, since I want to grab those hashtags from an account that we manage. So I'd be ok with that.
Yeah I figured that was the case, and that's fine too.

**Comment by oorestisime** [comment]
Right!

It looks like this endpoint would work for your use case https://developers.facebook.com/docs/instagram-api/reference/hashtag and i think i have the basic rights to tests this.
The way i am imagining it is having a `type` option `hashtag|username` defaulting to username so we don't break other people's setup and `hashtagId`

I ll have a look whether i can do this with public scraping as well so that i could support both ways of retrieving posts.

**Comment by luchoster** [comment]
that'd be awesome.
Thanks so much for that enhancement :)

**Comment by oorestisime** [comment]
Hello,

I ve made a lot of progress here, but i ve hit an issue. My instagram basic permission token does not allow me to use the graph api to retrieve of a hashtag from the API. https://developers.facebook.com/docs/instagram-api/hashtag-search I ll need to figure out how to get the Instagram Public Content Access feature but it seems i need to send an app for review and i am not sure i could since i don't have an app :D

In the meantime I ve managed to do this using the public scraping method and i managed to get `"totalCount": 66,` for the hashtag #snowing. I am going soon to PR this. Do you need  a particular hashtag? I could test on that as well to let you know beforehand how many posts i can retrieve.

**Comment by oorestisime** [comment]
So i published an example website with the plugin https://gatsby-src-instagram.netlify.com/ You can see the hashtags i retrieved.
Also published 0.4.0. let me know if you still need to source this from the graph api

**Comment by luchoster** [comment]
> Hello,
> 
> I ve made a lot of progress here, but i ve hit an issue. My instagram basic permission token does not allow me to use the graph api to retrieve of a hashtag from the API. https://developers.facebook.com/docs/instagram-api/hashtag-search I ll need to figure out how to get the Instagram Public Content Access feature but it seems i need to send an app for review and i am not sure i could since i don't have an app :D
> 
> In the meantime I ve managed to do this using the public scraping method and i managed to get `"totalCount": 66,` for the hashtag #snowing. I am going soon to PR this. Do you need a particular hashtag? I could test on that as well to let you know beforehand how many posts i can retrieve.

**Comment by luchoster** [comment]
Sorry I didn't mean to close it.

The hashtag I'm trying to get is: #vegas

**Comment by oorestisime** [comment]
Have you tried with the recent release to see if you get the results you wish?

**Comment by luchoster** [comment]
I have not yet, I'm hoping I'm gonna be able to do it this weekend.

**Comment by oorestisime** [comment]
kind reminder :)

**Comment by oorestisime** [comment]
Closing this! if you think there's something to improve let me know in a new issue or re-opening this one!
