### ISSUE TITLE
Source posts by user and hashtag

### ISSUE THREAD

**Issue by gmossong** [oorestisime/gatsby-source-instagram#58]
Is it possible with this plugin to source all posts from a user that contain a specific hashtag? For example, the user might be @racecars and the hashtag might be **#redcars**. So this would return all posts from the user @racecars with the **#redcars** hashtag.

Note that the user _isn't_ an account I own.

**Comment by oorestisime** [comment]
hm, the plugin won't do the filtering for you but i guess you could retrieve all the posts from user X and then when you build your queries or after using JS you can filter for the hashtag Y.

The problem is using the public scraping method only gets you to the last 12 posts so you wouldn't be able to retrieve all the posts.
