### ISSUE TITLE
Posts only update on build/restart

### ISSUE THREAD

**Issue by jgoggles** [oorestisime/gatsby-source-instagram#9]
Is there a way to query/scrape IG when the page loads in order to always see the latest posts?Right now the only way to get new posts is restarting `gatsby develop` or running `gatsby build`. Will using the IG Graph API accomplish this? It seems like a lot of trouble to go through to get a token just to display the last 6 Instagram posts on my site so I've held off and am using the scraper for now. Thanks!

Edit: is there a way to use the React component lifecycle (ie `componentDidMount`) for this?

**Comment by oorestisime** [comment]
Hello,

right now no there is no way to get the posts on each request. The only plugin i know that implements this kind of logic is the gatsby-source-filesystem and it is actually using a file watcher to accomplish it when using `gatsby develop`.

But even if there was a way to have a watcher on `gatsby develop`, there is no way (that i know) to have this on a live production site since the plugins are not in your source files. I ll ask around but it seems to me that in gatsby logic there is  no way to use component lifecycle for actually running plugins.

**Comment by jgoggles** [comment]
Thanks for the response. I got it to work how I want by taking your `getPublicInstagramPosts` function and moving that into my component, then calling it in the component's `componentDidMount` (passing in the IG username). So I sort of had to "extract" your plugin and use the raw source outside of the Gatsby plugin ecosystem.

**Comment by oorestisime** [comment]
yeah obviously this would work!
